spring:
   application:
      name: 02-greeting-service
management:
   endpoints:
      web:
         exposure:
            include:
               - '*'
greeting-service:
   greeting: "Hola"
   default-value: "Mundo"
